# Generated by Django 5.1.2 on 2024-11-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with that email address already exists."
                },
                max_length=254,
                unique=True,
            ),
        ),
    ]
