databases:
  - name: drivermatch
    plan: free
    databaseName: drivermatch
    user: drivermatch

services:
  - type: web
    plan: free
    name: drivermatch
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drivermatch
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4