# Generated by Django 5.1.2 on 2024-11-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
