# Generated by Django 5.1.2 on 2024-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_location_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
