# Generated by Django 5.1.2 on 2024-11-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_date_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="address",
            new_name="dropoff_location",
        ),
        migrations.AddField(
            model_name="location",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
