# Generated by Django 5.1.2 on 2024-10-14 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="type",
            field=models.CharField(
                choices=[("rider", "driver")], default="rider", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ]
            ),
        ),
    ]
