# Generated by Django 5.1.2 on 2024-10-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
