# Generated by Django 5.1.2 on 2024-10-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="pickup_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
