# Generated by Django 5.1.2 on 2024-10-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_pickup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dropoff_location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
