# Generated by Django 5.1.2 on 2024-10-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_booking_dropoff_location_booking_pickup_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
