# Generated by Django 5.1.2 on 2024-10-22 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_booking_guests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="type",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger",
            field=models.ManyToManyField(
                related_name="passenger_bookings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
