# Generated by Django 5.1.2 on 2024-11-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_remove_booking_type_remove_booking_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="passenger",
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger",
            field=models.TextField(blank=True, null=True),
        ),
    ]
