# Generated by Django 5.1.2 on 2024-11-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_remove_booking_passenger_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="passenger",
            new_name="locations",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="pickup_location",
            new_name="passengers",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="pickup_time",
            new_name="pickup_times",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="dropoff_location",
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
