# Generated by Django 5.1.2 on 2024-11-14 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_rename_passenger_booking_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="booking",
            name="locations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="passengers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_times",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
