# Generated by Django 5.1.2 on 2024-11-16 20:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_alter_booking_created_at_alter_booking_locations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="arrival_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
