# Generated by Django 5.1.2 on 2024-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_booking_arrival_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="starting_point",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="driver_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
