# Generated by Django 5.1.2 on 2025-01-06 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0017_booking_departure_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="starting_point",
        ),
    ]
