# Generated by Django 5.1.2 on 2025-01-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0018_remove_booking_arrival_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="starting_point",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
